# Generated by Django 2.2.4 on 2019-09-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_f', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Fuel',
                'verbose_name_plural': 'Fuel categories',
            },
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_gearb', models.CharField(default='not_null', max_length=31)),
            ],
            options={
                'verbose_name': 'Gearbox',
                'verbose_name_plural': 'Gearbox variety',
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_lay', models.CharField(default='not_null', max_length=31)),
            ],
            options={
                'verbose_name': 'Layout',
                'verbose_name_plural': 'Layout variety',
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_mak', models.CharField(default='not_null', max_length=255)),
            ],
            options={
                'verbose_name': 'Make',
                'verbose_name_plural': 'Make list',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_y', models.IntegerField(default=1900)),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Year list',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_mod', models.CharField(default='not_null', max_length=255)),
                ('car_make_mod', models.ForeignKey(default='not_null', on_delete=django.db.models.deletion.CASCADE, related_name='carMakeMod', to='car_sale.Make', verbose_name='Car make (model)')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Model list',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_engine_volume', models.IntegerField(default=0, verbose_name='Engine volume in cm3')),
                ('car_power', models.IntegerField(default=0, verbose_name='Power')),
                ('car_fuel', models.ForeignKey(default='not_null', on_delete=django.db.models.deletion.CASCADE, related_name='carFuel', to='car_sale.Fuel', verbose_name='Fuel type')),
                ('car_gearbox', models.ForeignKey(default='gearbox', on_delete=django.db.models.deletion.CASCADE, related_name='carGearbox', to='car_sale.Gearbox', verbose_name='Gearbox')),
                ('car_layout', models.ForeignKey(default='layout', on_delete=django.db.models.deletion.CASCADE, related_name='carLayout', to='car_sale.Gearbox', verbose_name='Layout')),
                ('car_make', models.ForeignKey(default='not_null', on_delete=django.db.models.deletion.CASCADE, related_name='carMake', to='car_sale.Make', verbose_name='Car make')),
                ('car_model', models.ForeignKey(default='not_null', on_delete=django.db.models.deletion.CASCADE, related_name='carModel', to='car_sale.Model', verbose_name='Car model')),
                ('car_year', models.ForeignKey(default=1900, on_delete=django.db.models.deletion.CASCADE, related_name='carYear', to='car_sale.Year', verbose_name='Production year')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Car list',
            },
        ),
    ]
